/**
 * Conformance reporting — the deliverable, not a side effect.
 *
 * The AWS provider is a *probe*: its value is the record of what a Launchfile
 * field maps to in AWS and what it can't. PROVIDERS.md §10 makes this a contract
 * obligation ("report gaps, not silent drops"). Three outcomes per field:
 *
 *   - mapped    — translated to one or more Terraform resources
 *   - gap       — the intent can't be honored on this target (logged, never dropped)
 *   - ignored   — a provider specialization safely ignored (RFC C / D-40): the
 *                 contract path covered it, so the hint is noise, not a failure
 */

export type Severity = "blocker" | "workaround" | "nice-to-have";

export interface Mapping {
	/** The Launchfile field, e.g. `requires:postgres` or `component.frontend.provides`. */
	field: string;
	/** The Terraform target it became, e.g. `aws_db_instance`. */
	target: string;
	/** Optional component scope. */
	component?: string;
}

export interface Gap {
	field: string;
	severity: Severity;
	reason: string;
	suggestion?: string;
	component?: string;
}

export interface Ignored {
	field: string;
	reason: string;
	component?: string;
}

/** Collects translation outcomes for one Launchfile. */
export class Conformance {
	readonly mapped: Mapping[] = [];
	readonly gaps: Gap[] = [];
	readonly ignored: Ignored[] = [];

	map(field: string, target: string, component?: string): void {
		this.mapped.push({ field, target, component });
	}

	gap(
		field: string,
		severity: Severity,
		reason: string,
		suggestion?: string,
		component?: string,
	): void {
		this.gaps.push({ field, severity, reason, suggestion, component });
	}

	ignore(field: string, reason: string, component?: string): void {
		this.ignored.push({ field, reason, component });
	}
}

const SEVERITY_ICON: Record<Severity, string> = {
	blocker: "🔴",
	workaround: "🟡",
	"nice-to-have": "🟢",
};

/** One Launchfile's outcome, for the aggregate conformance report. */
export interface ConformanceEntry {
	name: string;
	source: string;
	conformance: Conformance;
}

/** Render a single-file conformance section as Markdown. */
export function renderConformanceSection(entry: ConformanceEntry): string {
	const { name, source, conformance: c } = entry;
	const lines: string[] = [];
	lines.push(`### ${name}`);
	lines.push("");
	lines.push(
		`> Source: \`${source}\` — ${c.mapped.length} mapped, ${c.gaps.length} gap(s), ${c.ignored.length} ignored`,
	);
	lines.push("");

	if (c.mapped.length > 0) {
		lines.push("| Launchfile field | → Terraform | Component |");
		lines.push("|---|---|---|");
		for (const m of c.mapped) {
			lines.push(
				`| \`${m.field}\` | \`${m.target}\` | ${m.component ?? "—"} |`,
			);
		}
		lines.push("");
	}

	if (c.gaps.length > 0) {
		lines.push("**Gaps**");
		lines.push("");
		for (const g of c.gaps) {
			const scope = g.component ? ` _(${g.component})_` : "";
			const fix = g.suggestion ? ` — ${g.suggestion}` : "";
			lines.push(
				`- ${SEVERITY_ICON[g.severity]} \`${g.field}\`${scope}: ${g.reason}${fix}`,
			);
		}
		lines.push("");
	}

	if (c.ignored.length > 0) {
		lines.push(
			"**Ignored specializations** (contract sufficed — D-40 / RFC C)",
		);
		lines.push("");
		for (const i of c.ignored) {
			const scope = i.component ? ` _(${i.component})_` : "";
			lines.push(`- \`${i.field}\`${scope}: ${i.reason}`);
		}
		lines.push("");
	}

	return lines.join("\n");
}

/** Render the full aggregate conformance report across many Launchfiles. */
export function renderConformanceReport(entries: ConformanceEntry[]): string {
	const totalMapped = entries.reduce(
		(n, e) => n + e.conformance.mapped.length,
		0,
	);
	const totalGaps = entries.reduce((n, e) => n + e.conformance.gaps.length, 0);
	const totalIgnored = entries.reduce(
		(n, e) => n + e.conformance.ignored.length,
		0,
	);

	// Aggregate distinct gap fields by severity for the summary.
	const gapFields = new Map<string, Gap>();
	for (const e of entries) {
		for (const g of e.conformance.gaps) {
			if (!gapFields.has(g.field)) gapFields.set(g.field, g);
		}
	}

	const lines: string[] = [];
	lines.push("# AWS provider — conformance report");
	lines.push("");
	lines.push(
		"> Generated by `bun run conformance`. The AWS provider translates each Launchfile to Terraform (EC2 + RDS + ALB) and records what mapped, what gapped, and what was safely ignored. **No `apply` is ever run** — this is a spec-conformance probe (P-5, RFC C / #78).",
	);
	lines.push("");
	lines.push("## Summary");
	lines.push("");
	lines.push(`- **${entries.length}** Launchfile(s) translated`);
	lines.push(`- **${totalMapped}** field mappings`);
	lines.push(`- **${totalGaps}** gaps logged (never silently dropped)`);
	lines.push(`- **${totalIgnored}** specializations safely ignored`);
	lines.push("");

	if (gapFields.size > 0) {
		lines.push("### Distinct gaps");
		lines.push("");
		lines.push("| Field | Severity | Reason | Suggestion |");
		lines.push("|---|---|---|---|");
		for (const g of gapFields.values()) {
			lines.push(
				`| \`${g.field}\` | ${SEVERITY_ICON[g.severity]} ${g.severity} | ${g.reason} | ${g.suggestion ?? "—"} |`,
			);
		}
		lines.push("");
	}

	lines.push("## Per-Launchfile detail");
	lines.push("");
	for (const entry of entries) {
		lines.push(renderConformanceSection(entry));
	}

	return `${lines
		.join("\n")
		.replace(/\n{3,}/g, "\n\n")
		.trimEnd()}\n`;
}
