import { describe, expect, it } from "vitest";
import { Conformance, renderConformanceReport } from "../gaps.js";

function report(): string {
	const c = new Conformance();
	c.gap("requires:https-origin", "blocker", "no TLS listener");
	return renderConformanceReport([
		{ name: "demo", source: "demo/Launchfile", conformance: c },
	]);
}

describe("renderConformanceReport severity legend", () => {
	it("defines all three severities with their icons", () => {
		const text = report();
		expect(text).toContain(
			"- 🔴 `blocker`: nothing this probe emits meets the entry.",
		);
		expect(text).toContain(
			"- 🟡 `workaround`: the probe does not map the entry as declared.",
		);
		expect(text).toContain(
			"- 🟢 `nice-to-have`: the emitted Terraform is deployable without it.",
		);
	});

	it("states that no gap severity stops translate()", () => {
		expect(report()).toContain(
			"A gap of any severity never stops `translate()`",
		);
	});

	it("places the legend between the header blockquote and the summary", () => {
		const text = report();
		const header = text.indexOf("> Generated by `bun run conformance`");
		const legend = text.indexOf("**Gap severity**");
		const summary = text.indexOf("## Summary");
		expect(header).toBeGreaterThanOrEqual(0);
		expect(legend).toBeGreaterThan(header);
		expect(summary).toBeGreaterThan(legend);
	});

	it("prints the legend even when no Launchfile has a gap", () => {
		const text = renderConformanceReport([]);
		expect(text).toContain("**Gap severity**");
		expect(text).toContain("`nice-to-have`");
	});
});
